# Generated by Django 5.2 on 2025-04-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # No operations needed since we're using MongoEngine
    ]
