# Generated by Django 5.2 on 2025-04-19 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_members_projectmembership_project_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectrequest",
            unique_together={("project", "requester")},
        ),
    ]
