# Generated by Django 5.2 on 2025-04-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_projectrequest_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="code_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="projects.codefile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codefile",
            unique_together={("project", "filename")},
        ),
    ]
